2025-02-05 15:54:50,239 - waitress - INFO - Serving on http://0.0.0.0:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 15:54:51,359 - resume_api - INFO - Reading experience for company: excos - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 15:54:51,619 - resume_api - ERROR - Experience not found for company: excos - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:17
2025-02-05 15:54:54,150 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 16:16:24,883 - waitress - INFO - Serving on http://0.0.0.0:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 16:16:54,424 - waitress - INFO - Serving on http://0.0.0.0:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 16:17:28,332 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:11:24,054 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:11:30,554 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:11:49,774 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:12:55,500 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:12:58,518 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:13:03,055 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:13:11,262 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 17:14:01,280 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:14:06,738 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:15:36,964 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:15:37,157 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:23:03,910 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:23:05,931 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:23:06,465 - resume_api - ERROR - Unhandled Exception: company_name - http://localhost:8000/v1/experience/?language=fr - D:\WebProjects\alexi-courieux-resume-api\app\core\exceptionHandler.py:13
2025-02-05 17:24:12,534 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:24:14,744 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:24:15,270 - resume_api - ERROR - Unhandled Exception: company_name - http://localhost:8000/v1/experience/?language=fr - D:\WebProjects\alexi-courieux-resume-api\app\core\exceptionHandler.py:13
2025-02-05 17:24:52,646 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 17:24:53,172 - resume_api - ERROR - Unhandled Exception: company_name - http://localhost:8000/v1/experience/exco - D:\WebProjects\alexi-courieux-resume-api\app\core\exceptionHandler.py:13
2025-02-05 17:26:28,559 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:26:29,804 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 17:26:30,337 - resume_api - ERROR - Unhandled Exception: company_name - http://localhost:8000/v1/experience/exco
Traceback (most recent call last):
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\result.py", line 199, in _key_not_found
    self._key_fallback(key, None)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\result.py", line 138, in _key_fallback
    raise KeyError(key) from err
KeyError: 'company_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py", line 15, in read_experience
    experience = get_experience(db, company, language)
  File "D:\WebProjects\alexi-courieux-resume-api\app\crud\experienceCrud.py", line 14, in get_experience
    companyName=result.company_name,
                ^^^^^^^^^^^^^^^^^^^
  File "lib\\sqlalchemy\\cyextension\\resultproxy.pyx", line 66, in sqlalchemy.cyextension.resultproxy.BaseRow.__getattr__
  File "lib\\sqlalchemy\\cyextension\\resultproxy.pyx", line 63, in sqlalchemy.cyextension.resultproxy.BaseRow._get_by_key_impl
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\result.py", line 201, in _key_not_found
    raise AttributeError(ke.args[0]) from ke
AttributeError: company_name
 - D:\WebProjects\alexi-courieux-resume-api\app\core\exceptionHandler.py:15
2025-02-05 17:29:39,960 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:29:40,799 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 17:34:09,567 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:34:09,940 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 17:34:10,488 - resume_api - ERROR - Unhandled Exception: (pymysql.err.OperationalError) (1054, "Unknown column 'EXPERIENCE_I18N.companyName' in 'SELECT'")
[SQL: SELECT `EXPERIENCE`.id AS `EXPERIENCE_id`, `EXPERIENCE_I18N`.`companyName` AS `EXPERIENCE_I18N_companyName`, `EXPERIENCE_I18N`.`position` AS `EXPERIENCE_I18N_position`, `EXPERIENCE`.start_date AS `EXPERIENCE_start_date`, `EXPERIENCE`.end_date AS `EXPERIENCE_end_date`, `EXPERIENCE_I18N`.short_description AS `EXPERIENCE_I18N_short_description`, `EXPERIENCE_I18N`.description AS `EXPERIENCE_I18N_description` 
FROM `EXPERIENCE` INNER JOIN `EXPERIENCE_I18N` ON `EXPERIENCE`.id = `EXPERIENCE_I18N`.`experienceId` AND `EXPERIENCE_I18N`.language = %(language_1)s 
WHERE `EXPERIENCE`.id = %(id_1)s 
 LIMIT %(param_1)s]
[parameters: {'language_1': 'EN', 'id_1': 'exco', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/e3q8) - http://localhost:8000/v1/experience/exco
Traceback (most recent call last):
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
    ~~~~~~~~~~^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
    ~~~~~~~~~~~^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'EXPERIENCE_I18N.companyName' in 'SELECT'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py", line 15, in read_experience
    experience = get_experience(db, company, language)
  File "D:\WebProjects\alexi-courieux-resume-api\app\crud\experienceCrud.py", line 9, in get_experience
    filter(ExperienceModel.id == company).first()
                                          ~~~~~^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2754, in first
    return self.limit(1)._iter().first()  # type: ignore
           ~~~~~~~~~~~~~~~~~~~^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2853, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
        params,
        ^^^^^^^
        execution_options={"_sa_orm_load_options": self.load_options},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
    ~~~~~~~~~~^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
    ~~~~~~~~~~~^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'EXPERIENCE_I18N.companyName' in 'SELECT'")
[SQL: SELECT `EXPERIENCE`.id AS `EXPERIENCE_id`, `EXPERIENCE_I18N`.`companyName` AS `EXPERIENCE_I18N_companyName`, `EXPERIENCE_I18N`.`position` AS `EXPERIENCE_I18N_position`, `EXPERIENCE`.start_date AS `EXPERIENCE_start_date`, `EXPERIENCE`.end_date AS `EXPERIENCE_end_date`, `EXPERIENCE_I18N`.short_description AS `EXPERIENCE_I18N_short_description`, `EXPERIENCE_I18N`.description AS `EXPERIENCE_I18N_description` 
FROM `EXPERIENCE` INNER JOIN `EXPERIENCE_I18N` ON `EXPERIENCE`.id = `EXPERIENCE_I18N`.`experienceId` AND `EXPERIENCE_I18N`.language = %(language_1)s 
WHERE `EXPERIENCE`.id = %(id_1)s 
 LIMIT %(param_1)s]
[parameters: {'language_1': 'EN', 'id_1': 'exco', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
 - D:\WebProjects\alexi-courieux-resume-api\app\core\exceptionHandler.py:15
2025-02-05 17:36:07,372 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:36:08,058 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
2025-02-05 17:36:18,567 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:36:38,920 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:37:24,295 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:37:26,255 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:37:27,690 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:37:41,184 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:38:10,421 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:38:13,626 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:38:54,411 - waitress - INFO - Serving on http://127.0.0.1:8000 - D:\WebProjects\alexi-courieux-resume-api\.venv\Lib\site-packages\waitress\wasyncore.py:449
2025-02-05 17:38:54,859 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:38:56,851 - resume_api - INFO - Listing experiences - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:23
2025-02-05 17:39:01,851 - resume_api - INFO - Reading experience for company: exco - D:\WebProjects\alexi-courieux-resume-api\app\api\v1\endpoints\experienceEndpoint.py:12
